apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: userprofile
  name: userprofile
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userprofile