apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trips
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trips
      name: trips
    spec:
      containers:
      - image: registrytgz8460.azurecr.io/tripinsights/trips:1.0
        name: trips
        env:
        - name: SQL_SERVER
          value: "sqlservertgz8460.database.windows.net"
        - name: OPENAPI_DOCS_URI
          value: "http://changeme"  
        volumeMounts:
        - name: sqlsecret
          mountPath: "/secrets"  
      volumes:
      - name: sqlsecret
        secret:
          secretName: sqlsecret    
