apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tripviewer
  name: tripviewer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
status:
  loadBalancer: {}
