apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userjava
  name: userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userjava
      name: userjava
    spec:
      containers:
      - image: registrytgz8460.azurecr.io/tripinsights/user-java:1.0
        name: userjava
        env:
        - name: SQL_SERVER
          value: "sqlservertgz8460.database.windows.net"
        volumeMounts:
        - name: sqlsecret
          mountPath: "/secrets"          
      volumes:
      - name: sqlsecret
        secret:
          secretName: sqlsecret    