apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userprofile
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userprofile
      name: userprofile
    spec:
      containers:
      - image: registrytgz8460.azurecr.io/tripinsights/userprofile:1.0
        name: userprofile
        env:
        - name: SQL_SERVER
          value: "sqlservertgz8460.database.windows.net"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"  
        volumeMounts:
        - name: sqlsecret
          mountPath: "/secrets"          
      volumes:
      - name: sqlsecret
        secret:
          secretName: sqlsecret    